### ISSUE TITLE
대전모드 Timer 일시정지 issue

### ISSUE THREAD

**Issue by namepix** [Team14-SE-Tetris/Tetris#11]
`if (keyCode == KeyCode.SPACE) {
        	                if (gamePaused == false) {
        	                    timer.stop();
        	                } else {
        	                    timer.start();
        	                }`

대전모드 타이머모드에서 게임 일시정지 시 테트리스 동작만 정지하고 내부 타이머는 계속 흐르는 것을 발견

`if (keyCode == KeyCode.SPACE) {
        	                if (gamePaused == false) {
        	                    timer.stop();
        	                    Board2.timerStop();
        	                } else {
        	                    timer.start();
        	                    Board2.timerStart();
        	                }`
        	                
        	               
내부 타이머를 조작하는 함수를 추가하여 해결했다.

**Comment by githyj-jang** [comment]
Timer 테스트 완료
