### ISSUE TITLE
Test code 실행 issue

### ISSUE THREAD

**Issue by namepix** [Team14-SE-Tetris/Tetris#12]
Test code 실행에 문제가 생겼다.

1.Source 추가
   - Project -> Build Path -> Source 에 들어가서 Tetris/test 폴더를 추가하기

2.라이브러리 추가
   - hamcrest, testfx-core, testfx-junit 3개 jar 파일 추가
   - Project -> Build Path -> Library -> Classpath 에 Add External JARs 클릭후 다운 받은 1번 파일들 추가
   - Project -> Build Path -> Library에 Add Library 클릭 후 Jnit5라이브러리 클래스패스에 추가
   
3.테스트 코드 run configuration 설정
   - 테스트 코드 파일 우클릭 -> Run configuration -> (x)= Arguments 탭 -> VM argument에 밑의 코드 추가
 `--module-path [로컬 컴퓨터 javafx 설치 경로] --add-modules javafx.controls,javafx.fxml
--add-opens javafx.graphics/com.sun.javafx.application=ALL-UNNAMED `

위와같은 방법으로 해결.

**Comment by githyj-jang** [comment]
확인후 적용 완료
