### ISSUE TITLE
controller flow 점검

### ISSUE THREAD

**Issue by githyj-jang** [Team14-SE-Tetris/Tetris#7]
` if (mode == 1 || mode == 0) {
        		    Block itemtest = inGame.getCurrentBlock();
        		    KeyCode keyCode = event.getCode();
        		    if (delayflag) {
        		        if (gamePaused == false) {
        		            if (telpoflag == false) {
        		                if (keyCode == leftKey_Player1) {
        		                    inGame.moveLeft();
        		                } else if (keyCode == rightKey_Player1) {
        		                    inGame.moveRight(); // 오른쪽으로 이동
        		                } else if (keyCode == downKey_Player1) {

        		                    if (!(inGame.checkBlock())) {
        		                        delayflag = false;
        		                        if (itemtest.getItem() == 5 && !(inGame.checkCollisionBottom(inGame.getCurrentX(), inGame.getCurrentY()))) {
        		                            delayflag = true;
        		                            inGame.moveDown();
        		                        }
        		                    } else {
        		                        inGame.moveDown();
        		                    }
        		                } else if (keyCode == teleportKey_Player1) {
        		                    telpoflag = true;
        		                    if (itemtest.getItem() == 5 && !(inGame.checkCollisionBottom(inGame.getCurrentX(), inGame.getCurrentY()))) {
        		                        delayflag = true;
        		                        inGame.moveBottom();
        		                    } else {
        		                        inGame.moveBottom();
        		                        delayflag = false;
        		                    }
        		                } else if (keyCode == rotateKey_Player1) {
        		                    inGame.rotateBlock();
        		                } else if (keyCode == KeyCode.Q) {
        		                    timer.stop();
        		                    primaryStage.setScene(StartMenu.scene);
        		                    inGame.resetVariable();
        		                    score = 0;
        		                    System.out.println("점수: " + score);
        		                    System.out.println("점수: " + inGame.getScore());
        		                    // 게임 종료시, inGame의 dropSpeed와 Score를 초기상태로 초기화
        		                    centerStage(primaryStage);
        		                }
        		            }

        		            }

    		            if (keyCode == KeyCode.SPACE) {
    		                if (gamePaused == false) {
    		                    timer.stop();
    		                } else {
    		                    timer.start();
    		                }
    		                pauseGame(pane);
        		        }
        		    }`

오류 부분 확인 필요

**Comment by namepix** [comment]
점검 완료
