### ISSUE TITLE
item 오류

### ISSUE THREAD

**Issue by githyj-jang** [Team14-SE-Tetris/Tetris#8]
item 일부 오류 발생

**Comment by githyj-jang** [comment]
`public boolean moveDown() {
    	adjustScore(); // 점수 증가
    	adjustDropSpeed();
    	if (block.getItem()!=5) {
	    	if (moveBlock(0,1)) {
	    		dropBlocks++;
	    		return true;
	    	}
	    	else {
	    		int it = block.getItem();
	    		if(mode==1&&it>1) {
	    			switch(it) {
	    			case 2: // 주변 블럭 삭제
	    				
	    				for (int y = 0; y < block.height(); y++) {
	    		            for (int x = 0; x < block.width(); x++) {
	    		            	for (int i = -1; i < 2; i++) {
	    	    		            for (int j = -1; j < 2; j++){ 
	    	    		            	int newX = currentX + x + i;
	    			                    int newY = currentY + y + j;
	
	    			                    if (!(newX < 0 || newX >= BoardWidth || newY < 0 || newY >= BoardHeight)) {
	    			                    	board[newY][newX]=' ';
	    			                    }
	
	    	    		            }
	    	    		        }
	    		                
	    		            }
	    		        }
	    				break;
	    			case 3: // 1줄 랜덤 삭제
	    				for (int x = 0; x < BoardWidth; x++) {
	    					if (block.height()>1) {
	    						board[currentY+randomDelete_3][x] = 10;
	    					}
	    					else {
				                board[currentY][x] = 10;
	    					}
			            }
	    				break;
	    			case 4: // 1줄 삭제
	    				int[] where_4 = block.whereBlock(randomDelete_4);
	    				for (int x = 0; x < BoardWidth; x++) {
			                board[where_4[1]+currentY][x] = 10;
			            }
	    				block.changeShapeDetail(where_4[0],where_4[1],0);
	    				placeBlock();
	    				break;
	    			default:
	    				break;
	    			}
	    		}
	    		else {
	    			placeBlock();
	    		}
	    		return false;
	    	}
    	}`
점검 필요 할듯

**Comment by namepix** [comment]
점검 완료
