### ISSUE TITLE
UNIT

### ISSUE THREAD

**Issue by githyj-jang** [Team14-SE-Tetris/Tetris#9]
TEST CODE 추가

**Comment by namepix** [comment]
`@Test
    public void testAdjustScore() {
    	tetris = new Tetris(2); // level 2로 테트리스 게임 시작

        tetris.dropSpeed = 500_000_000;
        tetris.deleteItem = 2; // 삭제된 아이템 수
        tetris.dropBlocks = 5; // 떨어진 블럭 수
        tetris.deleteBar = 3; // 삭제된 라인 수
        tetris.adjustDropSpeed();
        // 예상되는 점수 계산
        int expectedScore = (1_000_000_000 - tetris.dropSpeed) / 1000 + tetris.deleteItem * 100 + tetris.dropBlocks * 10 + tetris.deleteBar * 100;

        // adjustScore 메서드 실행
        tetris.adjustScore();

        // 실제 결과와 예상 결과 비교
        assertEquals("점수 계산이 올바르지 않습니다.", expectedScore, tetris.score);
    }`
    
    
    
  테스트 코드 추가 완료
